/*
Given a string s, sort it in decreasing order based on the frequency of the characters. The frequency of a character is the number of times it appears in the string.

Return the sorted string. If there are multiple answers, return any of them.

 

Example 1:

Input: s = "tree"
Output: "eert"
Explanation: 'e' appears twice while 'r' and 't' both appear once.
So 'e' must appear before both 'r' and 't'. Therefore "eetr" is also a valid answer.
Example 2:

Input: s = "cccaaa"
Output: "aaaccc"
Explanation: Both 'c' and 'a' appear three times, so both "cccaaa" and "aaaccc" are valid answers.
Note that "cacaca" is incorrect, as the same characters must be together.
Example 3:

Input: s = "Aabb"
Output: "bbAa"
Explanation: "bbaA" is also a valid answer, but "Aabb" is incorrect.
Note that 'A' and 'a' are treated as two different characters.
 

Constraints:

1 <= s.length <= 5 * 105
s consists of uppercase and lowercase English letters and digits.
*/

#include <bits/stdc++.h>
using namespace std;

class Solution {
    static bool compare(vector<int> v1, vector<int> v2) {
        return v1[1] < v2[1];
    }
public:
    string frequencySort(string s) {
        string ans = "";
        ans.resize(s.size());
        unordered_map<char, int> m;
        multimap<int, char> mm;

        for (int i = 0; i < s.size(); i++)
        {
            m[s[i]]++;
        }
        
        for (auto &&i: m) {
            mm.insert({i.second, i.first});
        }

        int index = s.size() - 1;   
        for (auto &&i: mm) {
            for (int j = 0; j < i.first; j++)
            {
                ans[index] = i.second;
                index--;
            }
                        
        }

        return ans;
    }
};

int main() {
    Solution s;
    string rs = s.frequencySort("tree");
    cout << rs << endl;

    rs = s.frequencySort("cccaaa");
    cout << rs << endl;

    rs = s.frequencySort("Aabb");
    cout << rs << endl;
    rs = s.frequencySort("qcbkrbolomdwttlhqbldbuscinrsjrvmhjltvplkilimtfpkllobenptthmxfpfdiqrqjfbowklsnqvgfqaitsavhgraicmnvfklodarkcdikfocgxkrotwdubpuadbmerhlsrxdslrnamkwokedviqksjhtpsvpplxioxwsivnjrfiknxvwjqxmroawtxpxuntldepqlhwmmaahdxosiecqjqdmorqdvfklhkhukcvoqmdeajoqmndglphvpchtbmnadpjhhxrixdbcepwpdbxhfkfcgqvqqsmdqelijlksqtrhqpfxpqakadvrsmcrkpwtvanpibscdnufkcurgegxvigvvovwhdmabvqnmqxsqacueiddsdqxksrtgvhxhnftgrmanhrjhokcejbqchxjrbffftpncgsllnqktxbqanmbufonowkfamdckoghagdaqjudgaxvtoritlmmoasejeclgxdwbnxlnnscokkdirrqamiujphfdclghwpindgkjqxpmndxxolanjngrkaageffgtsxnpraxuwcgijtanqarhrjwawwclratfldpcasuhvufmngunxjmjunwcqopwxvpvkdvuccjsemcrwqbpbboghskihqfpogitihffqpwnusupfkjlvlxvkrcscmeexlqxfpbfbrlhnxkwjdkbmuhpejoxctugbknratxmwbjsgsovdlwjggougcxjounvvvbjsujjxwgeidhollucsifehvtopphjlelglswflqeosdmhicdvbkcoqjehnvljrnljclgacajifaxrdanskfwuaoathnxossakxjjsgnxkrvhddnrrgqceanjmwquqmkebltpkuxulnhmxbsxcedmpafoarmtpqggggcikpxkfraglfghvvhwnxgwbbtllvnwihuuifmiooxfiwkjjblhvnjlfnutemxeqhmdvwgwpuubgunfhphorlfuvoqvremqonxfjdgepkalvihlhhufxbcbaeoadwfdccpculskajkrfsqmjtbdqhicqgoucsblmgttnifqaidufrrgmagqedaptfjaopabtitwvhmwqqjvwobkkjdmkijqkaogpnlwbaavmlreqrocqjarbmjxemewnannuvrauqrwkrdcikkftrxrcrpjiqhheeofgpcrvfgthusiatdupgfenbgshteeofcpokppdcidlcxhhgdbdrcqjmncjnlonsirrphmqeonntbvhislrcxhirurgildxmrmkgcpsoatgiamgmwspidqqbdigkeenttiigjpkgomojfcfibfwugdsltvidwkowiwkhtwimjafvpjdmkwvvapwqlrnereuoiebcqtucrpkfoqkjcuoekgmxdffmwbvkjmnprgwfujpadwahppxaehljuxaenttlnmovmpvxmospfnonearsesvffbweebuaegtvdwsiagerumedgnmkmiifwsgtflrkmrogwtgiajvhqlktxhiptpfoacjsxjrbxenbexgvfaejccpsoonkjqtskaxqllgemrbonivsgbtojbvdltsshdubugqwaboempkmrpcflfqhgqkmxmiimbwcgdemwlkqoohdrfehvfedqphfjlqlaqtwrxkrvjsrkokmequpdhpdhwmxrwxmecbfekmfolwwihrhkckgvnjgtwicipatpfqoiuisqsvijjfdebglewrfvnnnvuspjtcjdghvlebwmnorjhhppbjpmujjixmitcoqqwibatijsberrdgbwqxgaufvsxxquutamnnlontbrowsvmmskcuhklbckutmeisurdegvurvlfomlehcchqmbtvxawihmwtjwrxiowmoiusaokpiopcnvdanuvvgdgokdvmrqvklgfdgtwgeocujpseuxrlujqsfbjdslqfvpoifmisqdamrwcptasdxouikxeotixdddrlgaavjmblvkkcdqatplkbsnfdlokfoavsiaofksnbudcetftdgxkkvdgedfisoarxukltrdvvgckpejufrtmoscohkfdeckhqcinoobhjugcbnurpdvjuckfvjhdrlxofjkfqkumtoakepnldjhplmblnaswsqgoajhuxfsnudpcokethwrqmrjqjgxvpkphpmpiuoniueddpvbxmibspjrehtmqqacbepktxgfxtautjqmrbxrpudkxaalhutievnrlaeabiqdtcfwiqmjvlxsjufedvkaillssgbivnupemjptxppglglkdrnkrotwfmawlevnatamvpnuppnbgqnlefigrxpmfoibngnicfxvofscqvsvsuwcjrnvueglrrecfhsgtudvwdvvkaxeqtrqiusjmwqmkwdjdodxcnewxshvmjlnhmtwcorbxudfqvwggujlqltxpkxsiagabanthqkmhxjitvujiickwmxhpsfmumanexiowcdekwsulpnkplbmsqiapsrlrvsmbqmbjlgirsuihcbjumdjfiwrhemixetgauhtwukattbwihbwpmckgmckonnrnberjkdlomaukiafgoukicfvhlldgiupvtlomdhtbeweeccfjotlwpudwfkuvtclvdsgigukhmhicawgbpekkdafmuwnewwdwajxgejahdibmtmqvtriufajrnhxlsqbadhsoegnsbdvssulwxktmwejvdnirpbdkutiqxlbbppvtghpmgfnknfmhejjamqtwcaqmnrfbnucboeexoufwlcbqacdgcfikolrrfhpfkdkkdmshhwkpadcjiqeuajbxpovqioqmhlwpvvsusuwodigaumgchtanfbtbfejvtuxplbsnofiteknnlnxqoteekktentqbhpueoimdnjaoeaxswtbfgbflutnrxlwillmenagwejwpltmvehtdhgluttriecmcoqbrjlcwflcfikmawqvqqbwnalhimkjpjhcrjjwsakebmnxbtggvkdpplbxcwlegdwpvgqmenteloufaejqjmdeslxrgslxanaieqslccqkthaxhrscoxjonjnnukebvosviwgtvkahjhidvjiucsvnkekuddvcfxowprfmndtbefusjvugxgakxfoevaxsahdlkqgorocjorfvmunrllrtvtrwixrbwxjebmrrlkeivessgpdtgiikehmtfqtxghrbueovrhbuswtlpfwfcfowliobmenurwklkrosuhcpmobhwpppfuswuphkulqihnfankaqeqwafflvevvkrsuefeinhedtidaktqfhbknglljhkgaeusexpghjdxowdjvxnlmaswqdxxmmfcbhhjdpcoxibgkxsoejkkvbiewgjrtmashsbsaeodvrjxoatdtwmwaledxxjcwpcwkmutmodglelkshhaeirwgpmllopcnfkftxgeovihajoipoweowltweqoltcargrijsaxgbgvvqmqmdxicqaeqjsjgwdfjkxxmfkbusnirjdlbaethorsmqapnpdqgbmbupevbivbuemrpmdwfhfflqtwowxkguaoksnqmlviokxrvgfqnvgmvqlgmecdlrspvwxvwmxuqbtelqssnikiikiaupdcvjemgjasfrbgrcjrsbbdpgcaofseaarikveemmbpdumgbgsrabeelaovwrqjhqfmedtahhkvadilrduuaabfiwgwbwuijfxodnaphskmcqnnadqrhgrfwqrmvvmapbhafkvkfwtttcsnouvqxumnnhboeejsilmqebabirtlcqatmafsxqcmgjmnoecfukioauslinldimxwbwghhdddaalrsfbcdqjdhkdjoidmunhxnoboagobdcnrqqmjouqxlddcjmdvwtqniqoirhuxabegilubmoejdxswrhcpxgcrllfvsqnvougxlijkgwxjawhxxlcsfwekvrnuexbsfcffqnloluqbqaddrhjncdhrhshnwoagfnhxhmcsdiggwngsklijwnloqumbidrdpengimnbgssdhnqfhxgfauqaaqsatingcxwsuevbncuovjbektncirwipgbrwumshouslgckhalphhagshlpgsmfwgtfjhovvjnplrevnfrhnihdidcfdbdimroderdhuakqgvtsfxeoavefkpimwudabvtuakkjeutglcgqrafdxeibddntxvewgmkpmsftgtqalqwqjouhkxcsqptkpcokkmtfrrcurgixmxdjltrrcvmgdmqcnvqtnhggopkfogfsbqfujvtkgnefdiodbnljimsrtuendrnsxreitwmbordqinlvejqgkcjpqjsfkibpqdxopvshcqrpdriwmtmhldjhoucuteqidxagpsgelkwrtomjmckhuwtcexntmumgqtvhsfqxaxsxqlrujordulohkilshhlaqbpkjohrkxmalhnhvpigdkexbreqtxhpcxogtvnrqkfvcmrmpviwjldsaiivbtocgpbuasiisqfvijnqpibtxwmhhhosqdbcnxkdqvrfijujsojfgjlhutpphnapqxxpfbxuugqblwcjklelloghicmrgsuerxcarejgtvftkvouhaasxabweedwxvsxelqwoqicfthmvijlkvlbqinbpptfximlitsqgfdalwxmnfufjcoaaeslsnnpakjwwpapqlepmqncjwmdoprqxwakterdrlijfxkcvkrqihrpjjuerflrdmpgmwxsluctvuhslstsivdsgqlbbcgsoaoafjpuedheomjoftcwtadupkqcgxauqjpqmpqqwrhojbgxagolrcaemgmgafcgxpivdxlxbgbgnbpnojgklsltwopnacubvcsqjaiimdphkglhgvltaimrmjravawmrruqhupmhgxxromoqdwvietvopsphwxauwqweciccbsgjlabvbmjlgaqmarjwtjfeimsicdtwkavsejburqwkosjpmphtbcsuijllehhkdimurnnncrfemsbglmroplajuprgqvngducqsfgjlgncaipkwqwffdonnwnixnnkjsavwamhoaxlkemjldoctmvhlgxcppixhdvmxiopsxsxswqfdmcujemxxwwsjcofmxcufdvrhlpwjncwhmkmhvuwphdkwipsioxvgkagvugbftkcntvavnftnjnkexrilptpdfanmjophwjdhjmkdegohevifihgvdglmumhueqaiphblggssuhahilwplxuoccqjwvtfldnxvtkdcexitriluommhcdgeuwtvcjxpandcoioeobplegfkpicwhkobgwqhmbspwaguikdvdincxtmafutwwkmrixsvlmpvgwxeibefevujlgipqaoqbjrtkrxwwrmhiagsgequihspapjwkkdefrgalfruoitwtokotlxriwrgnwphjeccnkjqlsxvckckagfapxrolkqecmsivvljpsmldialtwddgkwhrwojcewkiistxggtddnbtaguameqobgfckglemnixtpghvlgsngbkbajknhtpltardcmsieoodrbmecdmwoujtgjbqlkkbgqxiaeestdgkjwpllsiafkhwqgmvaggkhxmrrcrjsjpafdhrpspcldftowmuopexxexwghrojgqmgcfounqfxhdjisawmmuoewaaflgpatbwvbasdruatnabxcjsexvjxgbgqgnwiqtwairgfpttxxmbjggjwgiijepiviblhuwujjprqxugrlqdxvqcqcmjrivxoqifwbbbhtmtwqxkksmpcrgnddkoorikkaseovvfbfnnwmvokmpeiijshrchcbtbioiqnrjorqmfirwlrqksslrsvddsmgeuclscvnwgomrglqbpqxvrrbnmdlfbubtupxhamjleirtvbrxuvkpreuoakxrtrkkixraveebjhgdebeqkkhqlsctxlahbvqgbctuwuiqetnjclalpvobxfvfimnwshfroidevmdhnuumihoqnabctettlhapoxxthrkhbdwxesmmvvxqlcgkbpfojtpbngpmuoqotdqxsousrvrlckxsaokgjqunacvlonurcllqggwwuamqbskjbbmsdnndgeaqepqhwtvralqhpusiqbaqdarkxecchmcuwncjhlatbgegjsrcahigwlkawmnseljpvvlogmsoqvqdcdsxpeuekcprxnfuuxoaqjdpsutjvsnndffgqqscqfaqlpbapsraphcluufertcetcciidtpxnmtjdsvokkodjhlkmoadkbrsrrvrnhuxqvcjximarqdtoepwfqftoierbjekhoirarglucvfgnoxfhoafrckhimxemwdxhmutrxacshgjxaqqbawgsqhejsebasvgmhilumxcwckrhrvgsocxkpcxdvaqwjhvtkggegichhjivaoprquptwlpnwujvkjsffnwpeuevotnavddiwsilfdmrupehguhsxfshpkwqwbaksnsvwojlfjwnqcbkvxcrbpscgcsiasjrmlejdpclwowcsuihokvmscgrcnpmlprwwgselgklprsqbvjgbopbdgfddcmnahwrgucvgktdbkdoofepisartlbcibttpcrkmpfwftmsercoqnrkqwimtssurtloxikqbpuvibgbwxvgambgekhkssocqwegacsevcnlonpqslnhvccukxvkjmoecnokthhxpkcqagapovtjqaomcecfqosksnjlqpdwapbmgnjgloolrntgvsoewcklwifkgtmexhmwwalmavvxxbtclirneahbgvtmwcuifmcqtbesokktsvnptodijoxclebeiucbjvsadqoqmfuamaioouuhooexvoiblcvaelohxdpodplwsswatdvicquitsaspchfofnewmjecxhfhmocdcemgsjewicqvppaglxrjdkjsoimqmipnbltsgsfnjudvonrfgeepgmhddwfqymwkbanfuwbjmalorjxkuexbxoeuwrwnusobbfcxspbjbvpbhltoxpignqbopbiqdkaebbbkkevorsbvrdnqpwapjkvqxotajeuqsdtdtnealrhtnsnblhoeceklfaongrshtnbnwcawhjsdvgdadtmuqwwwcidjtxjjuwagjthiwksmbaopxdaxtqtcuuibhhdnvotwhakaguggxjatanlxukpofooatkwuhnjwvsrdshilkphgvlvccecunevuvgtoblrwnpuehtwiheeigdoioworsqnvpnssmamnwasjhabixwwquhfkobrpwrvujfcqxmsmqvvkbojadphxwglxmlvoiogbbinkkqtcmxlqnooltwfnmhbqiwifjjadjfbffcwqrmvteohxnckjgenviilvqjdtamhertnfxgtkfhoedndtvmhvodngfgxapehunegchuuoicbdmgtmaxbrkwqxraetnxrijlkpankwgvrujfjmivjqsacashbmcmewgkbtkltdgcvgrsekegjtilessdpcotcolqsoofaeixpcmfwhmshkdogfreofsfrriuxkcljkvgnhkgfsastdmraigkwwnqcxgagmbnvfeobgugbejuxbsucujwovafnxdlihaloenpbxrtuforrkvxljkoqrjebccffbjfsprrnbrwvmxslhfcunsucdkoqpiwusltciwuhffadrfvlxdnnlawfclrihxwxtovwmpqncexxopmcdoaojeojxcxccwnmutdogbfjqxvjinnxkpmxipcwkbogpotumjormotrrmqbsicufmphhielsqqtwviplrmrgncglvkobhkhupshxhlbanllqvmvdjhunosxwrkkisvbwqghpeordcjmvoigsdndjcegtjhlvccklvbxiqpilwrpepsbixiwjagrbmdcavtkfanpjdnjkcluoitxwdougbkjkcvhcgpbjjjgdtatwvhlsrmaljbxhlwwtenbtcwwcougokifppftjtlerqivnimaoatkstikvjavrhniobvvdekdvjdxhxkhdjxiaiofvjemnsxmtjxshhambdrfgbckcejunbwhqpasjuhrnjtigrnanwegkftcblsgxhjqocejoetpvbjxpuahjdtekdfxlnqfjbhxjkahltevkacjlhdblipnoupjocmljabgwpegjxdmfwuejtvwgxwsixlqdlpgisflxsaepkgmftassxwvaqrtnuadjxppvbfhesergehnlixbvdgircqaqtxliwgginhjvqbpwtuxweqrthvntvdaxvgisrktlufdbknmobpjahsemeunlbdvkrosvxvnuigticcsxvpfwshaxjbpmhonkpxbbqfgtikcdawxiamrkdwhfxnvtggbpajvhfeervaqcklmcboomnwpnmqvtobjalnfxnjaggsvesxivamllfbrakdbcqreojrcaiusbdxjsxmnqoacqnwunrmpatvuiihukovrsuxtdcbrtjbrlunsvxfhohmhhcftpimhlkseakvnheqbdtobigvdmmqwkhngmnjcrmjuahkrumlkarjknwlbrlibkfoxewelxdslmspfrldedoxnefjdolmhhoievjvkdgojukebxiqpukokxvwpsfmkarkgpivxvffvpxrmfttcswhrtfkwgaqinpgvtdkroaabwbghufkggbkblgfxkeisihtirrfbwinlartcmfxditqlfhpefbnqwrrbakhaumweggbnmdijxvxhjaalhqfcsnqgrwotjmjlpioqnapadojnabivrirpkmqadgunmjasuilsgdspfwfvclhklkbjofcxhjivwrkhufjmaudivgcwovncmmwghreluxjcwxpdqaowsurrcncbmxtufqopvgptlqrnfqwgixuivsulftexgkxcwwlupwuamnxotwjidurkagmfviifsfscommmwrjloflvhipbsoxdmirbdfowajvvfuabbnacbjnsspqamwvfbjlnwrojjmxduvjjbuhfpivetsmocddowqscxfifeqhlliovvoqwnktutretuvapugwqwqulsehhbuhnojklghxsbuopjvwpsjphckcltjwfprmauhenaqjgomtkrcuijdoxmdsfowlwuhfiwpaelekibatdfucaimjxdunamlikbpkteknaamihtqpdfdabqsriiurgujebwqdkaptbxguvevflaaxrihxlsthfxoxsstinxokgxmhqtoxqpkvartrfkkignnjwnprumxkrrwhrbdlvjbdqtebbaicjntcoqepwfldqesgpfvtbpobpfmwodfpgpcthlkqfcjferkluadwdrqapatxtlkomursevcoxmkjuhvvgrfmegpowlxgrkooeuqamhlxntmvcpmohjmuegmfnxccivrjgoiwgrffhojcurwffaoqdlollmdtqpmgklikdbjgegrbdulsqnohqcnkcjlrifnnqdqnlcgmocsaxjuvcjjjnosbawbujchghnbaokewdtgrihhwrlboqmeaouvmeepjbrscmsdeuqndvpxnpmfpkhdhedpjhmhwmidkurufrcnfiirkklnclnavkcqekrovjkvspqgtbbirxtxncbsitojeaspdpdmpqoprvocngenodhaxjgdsrejdvkexumskqvrxwepuwtfmufeggrbogenlklijljphdwtusjfgciplcfutqckfkihkhncpcvmxxsgaageucattewxhikaanfjffgxhevasghnpakgrgqteannoruafrgvbwvdkpjovjalmvdcechftprajmoswjcdvghohfqbdoocubtfdrnlhpnvtmrrplpujwljnidjslqtitaohdsfbgjslivoxpohoeddewcvejaopdtfxhwkqwvxjskaxvpfdknnfjegrzukrreldpqdmnqnfrhigmcvagsxxitlhbvqgvkatkkxgnemqnwweooiwkricknnadlhpphlqrkpffplrwfjrkvweeejhjtlevnqdhrfbsbkrfccbnfbwbngcwsrfmvobbvkdvbnxoxrdnvtwqwhkrhbjxkrudcwrwjwgjpmjndejnhedahtotcwqgfquoukdeslelcsxqpkovrnnokuapawhvdxofrkatqcvuuojnrupvepwandkwxqwdtnbqcqptsdssdaifkjwnwrfxjpewbngqpdoipbiuknspikdjsscfpekuwjmjmuwevrlliitoobnbljkabgtvbqwgtbefigpiwocsetbbxoeceagrowswdequkguuptxcctdvnkbnvvgidnnotjwgubqijbknhcblrxvfrwmsivdfpasgwqpxnoobrraxcecddtiarpirxhdqrscridwhwudpkgfuwielxwuanuialdpjjchojjsqwdocecctmxgjwjjuugjauahahkipaldapsqkgtwutaahaeitaevckxrncpglpacjprqhkbbpnmldnorphhlvvpximdilmbwcpbwjovueqtwpehcxkolinjqbdwwfqwhlpskqthvtvmjrxjnlrkfvjueaiaqclgguhdfejgwmuhulerrtltsdcjundahsujbfxnovxdppfvaemcphsickqhpqmwcovqdggpomhvpnqgvmhcghmrtrdaoskljmmtjxvstpxfgmesbdvjgdspxstrpbopffsrnieopiqcewchobviptucvmpmuxbrncxtwrlckvcfkbkqdwbhcpckghjbnkqcbcliedkgkiuvxpmlakpnoitoquppamgbcufjiuamjaimdoqjgfiltujgvrrhhlkphkhgbvorommxxanbeptasfstvpjbkblladpgpheakgrqbmutdjcfkbhvhgoupvsgwhwjtikxefppebgbrrljdkattphqqxpqhwmbukqomjolfjiqqrhfgoefranwuxkagxadkuvgksffwtntahwjspnnklawevdwqvdkwvdppagfgpuqhviexejjvwihxrbuhfwexhaaclpswvepxjvowvjjktekvlnqsahjnjfjutjeefgbqfmbobfgrbgwgdxcropsalcueqmmtakgiqxkhkeathemtjxtfxfhbngwktpkqmqfrsmmjpagqhhutvfsnmtpppscocmffsppssdfvbpqoihfwqqacthclbxgrprgbdrlmsgncosxpcthnakvcossmdtssqhvmfmkgbenrxbdsvntpgbihdeucfgpbxgrhbjmahmviumeiblrmtosrevdfqkvxcokjiiacfpubfsqhggqvwikwxevgcgtltojkjjonbnsedfkknwbjojbqodsevbkfjxwttlhiuwbhmtawuduafxowaatpxerntbidqptmorhecndfmuqlkusrveaacpbmluishnbhaamltdkwgdnjfgfifgqwmbssaqfiivktqbjkrufrioesnfotiqejxmtfknqglxgiqffllkoxegngutgcgadsswmhbkqdakeewuswildxicpwjwmopaoieaghnioaxaujeffrkauboelrnajodwelxkbvpxcmqppobkioarcgvkiiwhudckodsuusvplhlqfeeblmkveemwxcfeolegubnwiniqsjidnkxtfeqomgngapkworsbnmqxuparwtapqirqhuscpjhkkhwpossksftarwoliubonhcirpqkppkenthfdiwcctwbxeiohemwngcccsdgehwtkswrhkebwwkkfjisumkixfjxcxbogklwremlcawpnwvddlmxxljemepplntrtgrgbsxtlsslieattuwmhjlrueukcejjgwiltljqdbcggxedclfsuhxrgmbisfuefxrmxpruknvrrhpddjbciumslmurqhktrlcdmhpvpmlrwvttevcbqaevsfouhkvwbreokjcmcqmbxigdnxpkxmwkmgisnpuevrqosimrmqiqeakspqcedwkrapidkvwpxueteredfnhfmowccwtwujirpjixpmvvvjcvhgceegrrirkjvmirlcaurlowevqxxqruewgsstomqrvqipkfidsanfupawpvgsaxkcrwwegglwrhnbbcklogdqblekcwbwjxsirqjsjxjjffrjfircffntnshojmceluuspxtmqodbjdphxohbvpqoaesuenoewgxitnlcjvbpfcfenfjhpshkrbftlkpxcvtioqbnocskkitxbvc");
    cout << rs << endl;
}
